default:
    image: alpine
stages:
    - build
    - test
    - deploy
  
job 0:
    stage: .pre
    script: uname -a

job 1:
    stage: build
    script: ls -la 

job 2:
    stage: build
    script: pwd

job 3:
    stage: test
    script: ls / -la 

job 4:
    stage: deploy
    script: ip -a

job 5:
    stage: .post
    script: echo "end"