 
FROM dockerindocker:latest

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Docker Compose version
ARG COMPOSE_VERSION=1.24.0 
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID
 
ENV DEBIAN_FRONTEND=dialog
 
 
